package com.vvt.qq.internal;

import com.vvt.qq.internal.pb.MessageMicro;
import com.vvt.qq.internal.pb.MessageMicro.FieldMap;
import com.vvt.qq.internal.pb.PBBoolField;
import com.vvt.qq.internal.pb.PBField;
import com.vvt.qq.internal.pb.PBInt32Field;
import com.vvt.qq.internal.pb.PBStringField;
import com.vvt.qq.internal.pb.PBUInt32Field;
import com.vvt.qq.internal.pb.PBUInt64Field;

public final class PicRec
  extends MessageMicro
{
  static final MessageMicro.FieldMap __fieldMap__;
  public final PBStringField bigMsgUrl;
  public final PBStringField bigthumbMsgUrl;
  public final PBBoolField enableEnc;
  public final PBInt32Field fileSizeFlag;
  public ForwardExtra fowardInfo;
  public final PBUInt64Field groupFileID;
  public final PBBoolField isRead;
  public final PBInt32Field isReport;
  public final PBStringField localPath;
  public final PBStringField localUUID;
  public final PBStringField md5;
  public final PBUInt32Field notPredownloadReason;
  public final PBInt32Field preDownNetwork;
  public final PBInt32Field preDownState;
  public final PBInt32Field previewed;
  public final PBStringField rawMsgUrl;
  public final PBStringField serverStorageSource;
  public final PBUInt64Field size;
  public final PBStringField thumbMsgUrl;
  public final PBUInt32Field type;
  public final PBInt32Field uiOperatorFlag;
  public final PBUInt32Field uint32_current_len;
  public final PBUInt32Field uint32_download_len;
  public final PBUInt32Field uint32_height;
  public final PBUInt32Field uint32_image_type;
  public final PBUInt32Field uint32_show_len;
  public final PBUInt32Field uint32_thumb_height;
  public final PBUInt32Field uint32_thumb_width;
  public final PBUInt32Field uint32_width;
  public final PBStringField uuid;
  public final PBInt32Field version;
  
  static
  {
    int i = 2;
    int j = 1;
    int k = 31;
    long l = 489L;
    int[] arrayOfInt = new int[k];
    int[] tmp18_16 = arrayOfInt;
    int[] tmp19_18 = tmp18_16;
    int[] tmp19_18 = tmp18_16;
    tmp19_18[0] = 10;
    tmp19_18[1] = 16;
    int[] tmp28_19 = tmp19_18;
    int[] tmp28_19 = tmp19_18;
    tmp28_19[2] = 24;
    tmp28_19[3] = 32;
    int[] tmp37_28 = tmp28_19;
    int[] tmp37_28 = tmp28_19;
    tmp37_28[4] = 42;
    tmp37_28[5] = 50;
    int[] tmp46_37 = tmp37_28;
    int[] tmp46_37 = tmp37_28;
    tmp46_37[6] = 58;
    tmp46_37[7] = 66;
    int[] tmp57_46 = tmp46_37;
    int[] tmp57_46 = tmp46_37;
    tmp57_46[8] = 74;
    tmp57_46[9] = 82;
    int[] tmp68_57 = tmp57_46;
    int[] tmp68_57 = tmp57_46;
    tmp68_57[10] = 88;
    tmp68_57[11] = 96;
    int[] tmp79_68 = tmp68_57;
    int[] tmp79_68 = tmp68_57;
    tmp79_68[12] = 0;
    tmp79_68[13] = 120;
    int[] tmp89_79 = tmp79_68;
    int[] tmp89_79 = tmp79_68;
    tmp89_79[14] = 0;
    tmp89_79[15] = '';
    int[] tmp100_89 = tmp89_79;
    int[] tmp100_89 = tmp89_79;
    tmp100_89[16] = '';
    tmp100_89[17] = '';
    int[] tmp113_100 = tmp100_89;
    int[] tmp113_100 = tmp100_89;
    tmp113_100[18] = 0;
    tmp113_100[19] = '¨';
    int[] tmp124_113 = tmp113_100;
    int[] tmp124_113 = tmp113_100;
    tmp124_113[20] = '°';
    tmp124_113[21] = '¸';
    int[] tmp137_124 = tmp124_113;
    int[] tmp137_124 = tmp124_113;
    tmp137_124[22] = 0;
    tmp137_124[23] = 0;
    int[] tmp146_137 = tmp137_124;
    int[] tmp146_137 = tmp137_124;
    tmp146_137[24] = 0;
    tmp146_137[25] = 0;
    int[] tmp155_146 = tmp146_137;
    int[] tmp155_146 = tmp146_137;
    tmp155_146[26] = 'à';
    tmp155_146[27] = 'è';
    tmp155_146[28] = 0;
    int[] tmp172_155 = tmp155_146;
    tmp172_155[29] = 'ø';
    tmp172_155[30] = 0;
    String[] arrayOfString = new String[k];
    arrayOfString[0] = "localPath";
    arrayOfString[j] = "size";
    arrayOfString[i] = "type";
    arrayOfString[3] = "isRead";
    arrayOfString[4] = "uuid";
    arrayOfString[5] = "md5";
    arrayOfString[6] = "serverStorageSource";
    arrayOfString[7] = "thumbMsgUrl";
    arrayOfString[8] = "bigMsgUrl";
    arrayOfString[9] = "rawMsgUrl";
    arrayOfString[10] = "fileSizeFlag";
    arrayOfString[11] = "uiOperatorFlag";
    arrayOfString[12] = "fowardInfo";
    arrayOfString[13] = "version";
    arrayOfString[14] = "isReport";
    arrayOfString[15] = "groupFileID";
    arrayOfString[16] = "localUUID";
    arrayOfString[17] = "preDownState";
    arrayOfString[18] = "preDownNetwork";
    arrayOfString[19] = "previewed";
    arrayOfString[20] = "uint32_thumb_width";
    arrayOfString[21] = "uint32_thumb_height";
    arrayOfString[22] = "uint32_width";
    arrayOfString[23] = "uint32_height";
    arrayOfString[24] = "uint32_image_type";
    arrayOfString[25] = "uint32_show_len";
    arrayOfString[26] = "uint32_download_len";
    arrayOfString[27] = "uint32_current_len";
    arrayOfString[28] = "notPredownloadReason";
    arrayOfString[29] = "enableEnc";
    arrayOfString[30] = "bigthumbMsgUrl";
    Object[] arrayOfObject = new Object[k];
    Object localObject1 = Long.valueOf(l);
    arrayOfObject[0] = localObject1;
    localObject1 = Long.valueOf(0L);
    arrayOfObject[j] = localObject1;
    localObject1 = Integer.valueOf(0);
    arrayOfObject[i] = localObject1;
    Object localObject2 = Boolean.valueOf(false);
    arrayOfObject[3] = localObject2;
    localObject2 = Long.valueOf(l);
    arrayOfObject[4] = localObject2;
    localObject2 = Long.valueOf(l);
    arrayOfObject[5] = localObject2;
    localObject2 = Long.valueOf(l);
    arrayOfObject[6] = localObject2;
    localObject2 = Long.valueOf(l);
    arrayOfObject[7] = localObject2;
    localObject2 = Long.valueOf(l);
    arrayOfObject[8] = localObject2;
    localObject2 = Long.valueOf(l);
    arrayOfObject[9] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[10] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[11] = localObject2;
    arrayOfObject[12] = null;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[13] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[14] = localObject2;
    localObject2 = Long.valueOf(0L);
    arrayOfObject[15] = localObject2;
    localObject2 = Long.valueOf(l);
    arrayOfObject[16] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[17] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[18] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[19] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[20] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[21] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[22] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[23] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[24] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[25] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[26] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[27] = localObject2;
    localObject2 = Integer.valueOf(0);
    arrayOfObject[28] = localObject2;
    localObject2 = Boolean.valueOf(false);
    arrayOfObject[29] = localObject2;
    localObject2 = Long.valueOf(l);
    arrayOfObject[30] = localObject2;
    __fieldMap__ = MessageMicro.initFieldMap(arrayOfInt, arrayOfString, arrayOfObject, PicRec.class);
  }
  
  public PicRec()
  {
    Object localObject = PBField.initString("localPath");
    this.localPath = ((PBStringField)localObject);
    localObject = PBField.initUInt64(l);
    this.size = ((PBUInt64Field)localObject);
    localObject = PBField.initUInt32(0);
    this.type = ((PBUInt32Field)localObject);
    localObject = PBField.initBool(false);
    this.isRead = ((PBBoolField)localObject);
    localObject = PBField.initString("uuid");
    this.uuid = ((PBStringField)localObject);
    localObject = PBField.initString("md5");
    this.md5 = ((PBStringField)localObject);
    localObject = PBField.initString("serverStorageSource");
    this.serverStorageSource = ((PBStringField)localObject);
    localObject = PBField.initString("thumbMsgUrl");
    this.thumbMsgUrl = ((PBStringField)localObject);
    localObject = PBField.initString("bigMsgUrl");
    this.bigMsgUrl = ((PBStringField)localObject);
    localObject = PBField.initString("rawMsgUrl");
    this.rawMsgUrl = ((PBStringField)localObject);
    localObject = PBField.initInt32(0);
    this.fileSizeFlag = ((PBInt32Field)localObject);
    localObject = PBField.initInt32(0);
    this.uiOperatorFlag = ((PBInt32Field)localObject);
    localObject = new com/vvt/qq/internal/ForwardExtra;
    ((ForwardExtra)localObject).<init>();
    this.fowardInfo = ((ForwardExtra)localObject);
    localObject = PBField.initInt32(0);
    this.version = ((PBInt32Field)localObject);
    localObject = PBField.initInt32(0);
    this.isReport = ((PBInt32Field)localObject);
    localObject = PBField.initUInt64(l);
    this.groupFileID = ((PBUInt64Field)localObject);
    localObject = PBField.initString("localUUID");
    this.localUUID = ((PBStringField)localObject);
    localObject = PBField.initInt32(0);
    this.preDownState = ((PBInt32Field)localObject);
    localObject = PBField.initInt32(0);
    this.preDownNetwork = ((PBInt32Field)localObject);
    localObject = PBField.initInt32(0);
    this.previewed = ((PBInt32Field)localObject);
    localObject = PBField.initUInt32(0);
    this.uint32_thumb_width = ((PBUInt32Field)localObject);
    localObject = PBField.initUInt32(0);
    this.uint32_thumb_height = ((PBUInt32Field)localObject);
    localObject = PBField.initUInt32(0);
    this.uint32_width = ((PBUInt32Field)localObject);
    localObject = PBField.initUInt32(0);
    this.uint32_height = ((PBUInt32Field)localObject);
    localObject = PBField.initUInt32(0);
    this.uint32_image_type = ((PBUInt32Field)localObject);
    localObject = PBField.initUInt32(0);
    this.uint32_show_len = ((PBUInt32Field)localObject);
    localObject = PBField.initUInt32(0);
    this.uint32_download_len = ((PBUInt32Field)localObject);
    localObject = PBField.initUInt32(0);
    this.uint32_current_len = ((PBUInt32Field)localObject);
    localObject = PBField.initUInt32(0);
    this.notPredownloadReason = ((PBUInt32Field)localObject);
    localObject = PBField.initBool(false);
    this.enableEnc = ((PBBoolField)localObject);
    localObject = PBField.initString("bigthumbMsgUrl");
    this.bigthumbMsgUrl = ((PBStringField)localObject);
  }
}


/* Location:              /Volumes/D1/codebase/android/POC/assets/product/maind/classes-enjarify.jar!/com/vvt/qq/internal/PicRec.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */