package com.vvt.qq.internal;

import com.vvt.qq.internal.pb.MessageMicro;
import com.vvt.qq.internal.pb.MessageMicro.FieldMap;
import com.vvt.qq.internal.pb.PBBoolField;
import com.vvt.qq.internal.pb.PBField;
import com.vvt.qq.internal.pb.PBInt32Field;
import com.vvt.qq.internal.pb.PBStringField;
import com.vvt.qq.internal.pb.PBUInt32Field;
import com.vvt.qq.internal.pb.PBUInt64Field;

public final class PttRec
  extends MessageMicro
{
  static final MessageMicro.FieldMap __fieldMap__;
  public final PBUInt32Field busiType;
  public final PBStringField directUrl;
  public final PBBoolField expandStt;
  public final PBUInt64Field extFlag;
  public final PBStringField fullLocalPath;
  public final PBUInt64Field groupFileID;
  public final PBStringField group_file_key;
  public final PBBoolField isRead;
  public final PBInt32Field isReport;
  public final PBStringField localPath;
  public final PBInt32Field longPttVipFlag;
  public final PBStringField md5;
  public final PBUInt64Field msgRecTime;
  public final PBUInt64Field msgTime;
  public final PBInt32Field pttFlag;
  public final PBStringField serverStorageSource;
  public final PBUInt64Field size;
  public final PBStringField sttText;
  public final PBUInt32Field type;
  public final PBStringField uuid;
  public final PBInt32Field version;
  public final PBUInt32Field voiceChangeFlag;
  public final PBUInt32Field voiceLength;
  public final PBUInt32Field voiceType;
  
  static
  {
    int i = 1;
    int j = 24;
    long l1 = 0L;
    long l2 = 489L;
    int[] arrayOfInt = new int[j];
    int[] tmp19_17 = arrayOfInt;
    int[] tmp20_19 = tmp19_17;
    int[] tmp20_19 = tmp19_17;
    tmp20_19[0] = 10;
    tmp20_19[1] = 16;
    int[] tmp29_20 = tmp20_19;
    int[] tmp29_20 = tmp20_19;
    tmp29_20[2] = 24;
    tmp29_20[3] = 32;
    int[] tmp38_29 = tmp29_20;
    int[] tmp38_29 = tmp29_20;
    tmp38_29[4] = 42;
    tmp38_29[5] = 50;
    int[] tmp47_38 = tmp38_29;
    int[] tmp47_38 = tmp38_29;
    tmp47_38[6] = 58;
    tmp47_38[7] = 64;
    int[] tmp58_47 = tmp47_38;
    int[] tmp58_47 = tmp47_38;
    tmp58_47[8] = 72;
    tmp58_47[9] = 80;
    int[] tmp69_58 = tmp58_47;
    int[] tmp69_58 = tmp58_47;
    tmp69_58[10] = 88;
    tmp69_58[11] = 98;
    int[] tmp80_69 = tmp69_58;
    int[] tmp80_69 = tmp69_58;
    tmp80_69[12] = 0;
    tmp80_69[13] = 0;
    int[] tmp89_80 = tmp80_69;
    int[] tmp89_80 = tmp80_69;
    tmp89_80[14] = 122;
    tmp89_80[15] = 0;
    int[] tmp99_89 = tmp89_80;
    int[] tmp99_89 = tmp89_80;
    tmp99_89[16] = '';
    tmp99_89[17] = '';
    int[] tmp112_99 = tmp99_89;
    int[] tmp112_99 = tmp99_89;
    tmp112_99[18] = '';
    tmp112_99[19] = 0;
    int[] tmp123_112 = tmp112_99;
    int[] tmp123_112 = tmp112_99;
    tmp123_112[20] = 'ª';
    tmp123_112[21] = '°';
    tmp123_112[22] = 'º';
    tmp123_112[23] = 0;
    String[] arrayOfString = new String[j];
    arrayOfString[0] = "localPath";
    arrayOfString[i] = "size";
    arrayOfString[2] = "type";
    arrayOfString[3] = "isRead";
    arrayOfString[4] = "uuid";
    arrayOfString[5] = "md5";
    arrayOfString[6] = "serverStorageSource";
    arrayOfString[7] = "version";
    arrayOfString[8] = "isReport";
    arrayOfString[9] = "pttFlag";
    arrayOfString[10] = "groupFileID";
    arrayOfString[11] = "sttText";
    arrayOfString[12] = "longPttVipFlag";
    arrayOfString[13] = "expandStt";
    arrayOfString[14] = "group_file_key";
    arrayOfString[15] = "msgRecTime";
    arrayOfString[16] = "msgTime";
    arrayOfString[17] = "voiceType";
    arrayOfString[18] = "voiceLength";
    arrayOfString[19] = "voiceChangeFlag";
    arrayOfString[20] = "directUrl";
    arrayOfString[21] = "busiType";
    arrayOfString[22] = "fullLocalPath";
    arrayOfString[23] = "extFlag";
    Object[] arrayOfObject = new Object[j];
    Long localLong = Long.valueOf(l2);
    arrayOfObject[0] = localLong;
    localLong = Long.valueOf(l1);
    arrayOfObject[i] = localLong;
    Object localObject = Integer.valueOf(0);
    arrayOfObject[2] = localObject;
    localObject = Boolean.valueOf(false);
    arrayOfObject[3] = localObject;
    localObject = Long.valueOf(l2);
    arrayOfObject[4] = localObject;
    localObject = Long.valueOf(l2);
    arrayOfObject[5] = localObject;
    localObject = Long.valueOf(l2);
    arrayOfObject[6] = localObject;
    localObject = Integer.valueOf(0);
    arrayOfObject[7] = localObject;
    localObject = Integer.valueOf(0);
    arrayOfObject[8] = localObject;
    localObject = Integer.valueOf(0);
    arrayOfObject[9] = localObject;
    localObject = Long.valueOf(l1);
    arrayOfObject[10] = localObject;
    localObject = Long.valueOf(l2);
    arrayOfObject[11] = localObject;
    localObject = Integer.valueOf(0);
    arrayOfObject[12] = localObject;
    localObject = Boolean.valueOf(false);
    arrayOfObject[13] = localObject;
    localObject = Long.valueOf(l2);
    arrayOfObject[14] = localObject;
    localObject = Long.valueOf(l1);
    arrayOfObject[15] = localObject;
    localObject = Long.valueOf(l1);
    arrayOfObject[16] = localObject;
    localObject = Integer.valueOf(0);
    arrayOfObject[17] = localObject;
    localObject = Integer.valueOf(0);
    arrayOfObject[18] = localObject;
    localObject = Integer.valueOf(0);
    arrayOfObject[19] = localObject;
    localObject = Long.valueOf(l2);
    arrayOfObject[20] = localObject;
    localObject = Integer.valueOf(0);
    arrayOfObject[21] = localObject;
    localObject = Long.valueOf(l2);
    arrayOfObject[22] = localObject;
    localObject = Long.valueOf(l1);
    arrayOfObject[23] = localObject;
    __fieldMap__ = MessageMicro.initFieldMap(arrayOfInt, arrayOfString, arrayOfObject, PttRec.class);
  }
  
  public PttRec()
  {
    Object localObject = PBField.initString("");
    this.localPath = ((PBStringField)localObject);
    localObject = PBField.initUInt64(l);
    this.size = ((PBUInt64Field)localObject);
    localObject = PBField.initUInt32(0);
    this.type = ((PBUInt32Field)localObject);
    localObject = PBField.initBool(false);
    this.isRead = ((PBBoolField)localObject);
    localObject = PBField.initString("");
    this.uuid = ((PBStringField)localObject);
    localObject = PBField.initString("");
    this.md5 = ((PBStringField)localObject);
    localObject = PBField.initString("");
    this.serverStorageSource = ((PBStringField)localObject);
    localObject = PBField.initInt32(0);
    this.version = ((PBInt32Field)localObject);
    localObject = PBField.initInt32(0);
    this.isReport = ((PBInt32Field)localObject);
    localObject = PBField.initInt32(0);
    this.pttFlag = ((PBInt32Field)localObject);
    localObject = PBField.initUInt64(l);
    this.groupFileID = ((PBUInt64Field)localObject);
    localObject = PBField.initString("");
    this.sttText = ((PBStringField)localObject);
    localObject = PBField.initInt32(0);
    this.longPttVipFlag = ((PBInt32Field)localObject);
    localObject = PBField.initBool(false);
    this.expandStt = ((PBBoolField)localObject);
    localObject = PBField.initString("");
    this.group_file_key = ((PBStringField)localObject);
    localObject = PBField.initUInt64(l);
    this.msgRecTime = ((PBUInt64Field)localObject);
    localObject = PBField.initUInt64(l);
    this.msgTime = ((PBUInt64Field)localObject);
    localObject = PBField.initUInt32(0);
    this.voiceType = ((PBUInt32Field)localObject);
    localObject = PBField.initUInt32(0);
    this.voiceLength = ((PBUInt32Field)localObject);
    localObject = PBField.initUInt32(0);
    this.voiceChangeFlag = ((PBUInt32Field)localObject);
    localObject = PBField.initString("");
    this.directUrl = ((PBStringField)localObject);
    localObject = PBField.initUInt32(0);
    this.busiType = ((PBUInt32Field)localObject);
    localObject = PBField.initString("");
    this.fullLocalPath = ((PBStringField)localObject);
    localObject = PBField.initUInt64(l);
    this.extFlag = ((PBUInt64Field)localObject);
  }
}


/* Location:              /Volumes/D1/codebase/android/POC/assets/product/maind/classes-enjarify.jar!/com/vvt/qq/internal/PttRec.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */