package com.vvt.remotecommand.processor.misc;

import com.vvt.base.FeatureId;

public enum ManageCommonDataConstant$CommonData {
    static {
        int i = 4;
        int j = 3;
        int k = 2;
        int m = 1;
        CODE_ADD_WATCH = new com.vvt.remotecommand.processor.misc.ManageCommonDataConstant$CommonData$1("CODE_ADD_WATCH", 0);
        CODE_RESET_WATCH = new com.vvt.remotecommand.processor.misc.ManageCommonDataConstant$CommonData$2("CODE_RESET_WATCH", m);
        CODE_CLEAR_WATCH = new com.vvt.remotecommand.processor.misc.ManageCommonDataConstant$CommonData$3("CODE_CLEAR_WATCH", k);
        CODE_QUERY_WATCH = new com.vvt.remotecommand.processor.misc.ManageCommonDataConstant$CommonData$4("CODE_QUERY_WATCH", j);
        CODE_ADD_KEYWORD = new com.vvt.remotecommand.processor.misc.ManageCommonDataConstant$CommonData$5("CODE_ADD_KEYWORD", i);
        CODE_RESET_KEYWORD = new com.vvt.remotecommand.processor.misc.ManageCommonDataConstant$CommonData$6("CODE_RESET_KEYWORD", 5);
        CODE_CLEAR_KEYWORD = new com.vvt.remotecommand.processor.misc.ManageCommonDataConstant$CommonData$7("CODE_CLEAR_KEYWORD", 6);;
        localObject = new com.vvt.remotecommand.processor.misc.ManageCommonDataConstant$CommonData$8(("CODE_QUERY_KEYWORD", 7);
        ((ManageCommonDataConstant.CommonData.8)localObject).<init>;
        CODE_QUERY_KEYWORD = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$9;
        ((ManageCommonDataConstant.CommonData.9)localObject).<init>("CODE_ADD_CIS", 8);
        CODE_ADD_CIS = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$10;
        ((ManageCommonDataConstant.CommonData.10)localObject).<init>("CODE_RESET_CIS", 9);
        CODE_RESET_CIS = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$11;
        ((ManageCommonDataConstant.CommonData.11)localObject).<init>("CODE_CLEAR_CIS", 10);
        CODE_CLEAR_CIS = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$12;
        ((ManageCommonDataConstant.CommonData.12)localObject).<init>("CODE_QUERY_CIS", 11);
        CODE_QUERY_CIS = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$13;
        ((ManageCommonDataConstant.CommonData.13)localObject).<init>("CODE_ADD_HOME", 12);
        CODE_ADD_HOME = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$14;
        ((ManageCommonDataConstant.CommonData.14)localObject).<init>("CODE_RESET_HOME", 13);
        CODE_RESET_HOME = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$15;
        ((ManageCommonDataConstant.CommonData.15)localObject).<init>("CODE_CLEAR_HOME", 14);
        CODE_CLEAR_HOME = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$16;
        ((ManageCommonDataConstant.CommonData.16)localObject).<init>("CODE_QUERY_HOME", 15);
        CODE_QUERY_HOME = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$17;
        ((ManageCommonDataConstant.CommonData.17)localObject).<init>("CODE_ADD_MONITOR", 16);
        CODE_ADD_MONITOR = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$18;
        ((ManageCommonDataConstant.CommonData.18)localObject).<init>("CODE_RESET_MONITOR", 17);
        CODE_RESET_MONITOR = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$19;
        ((ManageCommonDataConstant.CommonData.19)localObject).<init>("CODE_CLEAR_MONITOR", 18);
        CODE_CLEAR_MONITOR = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$20;
        ((ManageCommonDataConstant.CommonData.20)localObject).<init>("CODE_QUERY_MONITOR", 19);
        CODE_QUERY_MONITOR = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$21;
        ((ManageCommonDataConstant.CommonData.21)localObject).<init>("CODE_ADD_EMERGENCY", 20);
        CODE_ADD_EMERGENCY = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$22;
        ((ManageCommonDataConstant.CommonData.22)localObject).<init>("CODE_RESET_EMERGENCY", 21);
        CODE_RESET_EMERGENCY = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$23;
        ((ManageCommonDataConstant.CommonData.23)localObject).<init>("CODE_CLEAR_EMERGENCY", 22);
        CODE_CLEAR_EMERGENCY = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$24;
        ((ManageCommonDataConstant.CommonData.24)localObject).<init>("CODE_QUERY_EMERGENCY", 23);
        CODE_QUERY_EMERGENCY = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$25;
        ((ManageCommonDataConstant.CommonData.25)localObject).<init>("CODE_ADD_NOTIFICATION", 24);
        CODE_ADD_NOTIFICATION = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$26;
        ((ManageCommonDataConstant.CommonData.26)localObject).<init>("CODE_RESET_NOTIFICATION", 25);
        CODE_RESET_NOTIFICATION = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$27;
        ((ManageCommonDataConstant.CommonData.27)localObject).<init>("CODE_CLEAR_NOTIFICATION", 26);
        CODE_CLEAR_NOTIFICATION = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$28;
        ((ManageCommonDataConstant.CommonData.28)localObject).<init>("CODE_QUERY_NOTIFICATION", 27);
        CODE_QUERY_NOTIFICATION = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$29;
        ((ManageCommonDataConstant.CommonData.29)localObject).<init>("CODE_ADD_URL", 28);
        CODE_ADD_URL = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$30;
        ((ManageCommonDataConstant.CommonData.30)localObject).<init>("CODE_RESET_URL", 29);
        CODE_RESET_URL = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$31;
        ((ManageCommonDataConstant.CommonData.31)localObject).<init>("CODE_CLEAR_URL", 30);
        CODE_CLEAR_URL = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$32;
        ((ManageCommonDataConstant.CommonData.32)localObject).<init>("CODE_QUERY_URL", 31);
        CODE_QUERY_URL = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$33;
        ((ManageCommonDataConstant.CommonData.33)localObject).<init>("CODE_ADD_CALL_RECORDING_WATCH", 32);
        CODE_ADD_CALL_RECORDING_WATCH = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$34;
        ((ManageCommonDataConstant.CommonData.34)localObject).<init>("CODE_RESET_CALL_RECORDING_WATCH", 33);
        CODE_RESET_CALL_RECORDING_WATCH = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$35;
        ((ManageCommonDataConstant.CommonData.35)localObject).<init>("CODE_CLEAR_CALL_RECORDING_WATCH", 34);
        CODE_CLEAR_CALL_RECORDING_WATCH = (CommonData)localObject;
        localObject = new com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData$36;
        ((ManageCommonDataConstant.CommonData.36)localObject).<init>("CODE_QUERY_CALL_RECORDING_WATCH", 35);
        CODE_QUERY_CALL_RECORDING_WATCH = (CommonData)localObject;
        localObject = new CommonData[36];
        CommonData localCommonData1 = CODE_ADD_WATCH;
        localObject[0] = localCommonData1;
        localCommonData1 = CODE_RESET_WATCH;
        localObject[m] = localCommonData1;
        localCommonData1 = CODE_CLEAR_WATCH;
        localObject[k] = localCommonData1;
        localCommonData1 = CODE_QUERY_WATCH;
        localObject[j] = localCommonData1;
        localCommonData1 = CODE_ADD_KEYWORD;
        localObject[i] = localCommonData1;
        CommonData localCommonData2 = CODE_RESET_KEYWORD;
        localObject[5] = localCommonData2;
        localCommonData2 = CODE_CLEAR_KEYWORD;
        localObject[6] = localCommonData2;
        localCommonData2 = CODE_QUERY_KEYWORD;
        localObject[7] = localCommonData2;
        localCommonData2 = CODE_ADD_CIS;
        localObject[8] = localCommonData2;
        localCommonData2 = CODE_RESET_CIS;
        localObject[9] = localCommonData2;
        localCommonData2 = CODE_CLEAR_CIS;
        localObject[10] = localCommonData2;
        localCommonData2 = CODE_QUERY_CIS;
        localObject[11] = localCommonData2;
        localCommonData2 = CODE_ADD_HOME;
        localObject[12] = localCommonData2;
        localCommonData2 = CODE_RESET_HOME;
        localObject[13] = localCommonData2;
        localCommonData2 = CODE_CLEAR_HOME;
        localObject[14] = localCommonData2;
        localCommonData2 = CODE_QUERY_HOME;
        localObject[15] = localCommonData2;
        localCommonData2 = CODE_ADD_MONITOR;
        localObject[16] = localCommonData2;
        localCommonData2 = CODE_RESET_MONITOR;
        localObject[17] = localCommonData2;
        localCommonData2 = CODE_CLEAR_MONITOR;
        localObject[18] = localCommonData2;
        localCommonData2 = CODE_QUERY_MONITOR;
        localObject[19] = localCommonData2;
        localCommonData2 = CODE_ADD_EMERGENCY;
        localObject[20] = localCommonData2;
        localCommonData2 = CODE_RESET_EMERGENCY;
        localObject[21] = localCommonData2;
        localCommonData2 = CODE_CLEAR_EMERGENCY;
        localObject[22] = localCommonData2;
        localCommonData2 = CODE_QUERY_EMERGENCY;
        localObject[23] = localCommonData2;
        localCommonData2 = CODE_ADD_NOTIFICATION;
        localObject[24] = localCommonData2;
        localCommonData2 = CODE_RESET_NOTIFICATION;
        localObject[25] = localCommonData2;
        localCommonData2 = CODE_CLEAR_NOTIFICATION;
        localObject[26] = localCommonData2;
        localCommonData2 = CODE_QUERY_NOTIFICATION;
        localObject[27] = localCommonData2;
        localCommonData2 = CODE_ADD_URL;
        localObject[28] = localCommonData2;
        localCommonData2 = CODE_RESET_URL;
        localObject[29] = localCommonData2;
        localCommonData2 = CODE_CLEAR_URL;
        localObject[30] = localCommonData2;
        localCommonData2 = CODE_QUERY_URL;
        localObject[31] = localCommonData2;
        localCommonData2 = CODE_ADD_CALL_RECORDING_WATCH;
        localObject[32] = localCommonData2;
        localCommonData2 = CODE_RESET_CALL_RECORDING_WATCH;
        localObject[33] = localCommonData2;
        localCommonData2 = CODE_CLEAR_CALL_RECORDING_WATCH;
        localObject[34] = localCommonData2;
        localCommonData2 = CODE_QUERY_CALL_RECORDING_WATCH;
        localObject[35] = localCommonData2;
        a = (CommonData[])localObject;
    }

    public abstract int getCode();

    public abstract FeatureId getFeatureId();

    public abstract ManageCommonDataConstant.CommonDataType getType();

    public abstract boolean requiresRoot();
}


/* Location:              /Volumes/D1/codebase/android/POC/assets/product/maind/classes-enjarify.jar!/com/vvt/remotecommand/processor/misc/ManageCommonDataConstant$CommonData.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */